#!/bin/bash
#
# Set up gnu-arm-embedded toolchain (newest major version at the moment of creation)

wget https://developer.arm.com/-/media/Files/downloads/gnu-rm/9-2019q4/RC2.1/gcc-arm-none-eabi-9-2019-q4-major-x86_64-linux.tar.bz2
tar xjf gcc-arm-none-eabi-9-2019-q4-major-x86_64-linux.tar.bz2
sudo mv gcc-arm-none-eabi-9-2019-q4-major /opt
export PATH=$PATH:/opt/gcc-arm-none-eabi-9-2019-q4-major/bin
